ALTER TABLE folios ADD COLUMN signature LONGTEXT NULL;
ALTER TABLE users ADD COLUMN status VARCHAR(255) NOT NULL DEFAULT 'active';
ALTER TABLE users ADD COLUMN permissions JSON NULL;
ALTER TABLE users ADD COLUMN ownerSeal LONGTEXT NULL;
